apiVersion: apps/v1
kind: Deployment
metadata:
  name: chri-portfolio
  namespace: apps
  labels:
    app: chri-portfolio
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: chri-portfolio
  template:
    metadata:
      labels:
        app: chri-portfolio
    spec:
      imagePullSecrets:
        - name: registry-secret
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: d4knezsl1me/chri-portfolio:latest # overwritten by CI (kustomize)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: next-cache
              mountPath: /app/.next/cache
          envFrom:
            - secretRef:
                name: chri-portfolio-secrets
      volumes:
        - name: tmp
          emptyDir: {}
        - name: next-cache
          emptyDir: {}
